### ISSUE TITLE
sayılar private değişkende tutabilirsin

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/burak_imdat_onboard#1]
https://github.com/VBT-FlutterCamp/burak_imdat_onboard/blob/4111b425fbc85a9ac08f34bf52761b0e170b255f/lib/feature/onboard/view/onboard_view.dart#L101

**Comment by burakJs** [comment]
https://github.com/VBT-FlutterCamp/burak_imdat_onboard/blob/2fdc0b9bd6a182a6e9a2ad4a658b09999949ac2f/lib/feature/onboard/view/onboard_view.dart#L103

https://github.com/VBT-FlutterCamp/burak_imdat_onboard/blob/2fdc0b9bd6a182a6e9a2ad4a658b09999949ac2f/lib/feature/onboard/view/onboard_view.dart#L118

Sayılar private değişkene atandı ve yeni commit atıldı
